#!/bin/sh

uci set firewall.@defaults[0].flow_offloading=1
uci commit firewall

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@flowoffload[-1]
	add ucitrack flowoffload
	set ucitrack.@flowoffload[-1].init=flowoffload
	commit ucitrack
EOF

sed -i "s/4.14.131/$(uname -r)/g" /usr/lib/lua/luci/model/cbi/flowoffload.lua

exit 0
