#!/bin/sh /etc/rc.common
START=99
STOP=10


start() {
	flag=$(ps | grep "serverchan/serverchan" | grep -v "grep" | wc -l)
	if [ $flag -eq 0 ] ;then
		/usr/sbin/serverchan/serverchan &
	fi
}

stop() {
	kill -9 $(ps | grep serverchan | grep -v "grep" | awk '{print $1}') >/dev/null 2>&1
}
