#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@openclash[-1]
	add ucitrack openclash
	set ucitrack.@openclash[-1].init=openclash
	commit ucitrack
EOF

[ ! -f /etc/openclash/clash ] && ln -s /usr/bin/clash /etc/openclash/clash

rm -f /tmp/luci-indexcache
exit 0
