#!/bin/sh /etc/rc.common
# Copyright (C) 2019 By [CTCGFW] Project OpenWRT

START=90
STOP=10

enabled="$(uci get baidupcs-web.config.enabled)"
port="$(uci get baidupcs-web.config.port)"
dl_dir="$(uci get baidupcs-web.config.dl_dir)"

start() {
	stop
	[ "$enabled" == "1" ] || exit 0
	mkdir -p "${dl_dir}"
	BaiduPCS-Go config set -savedir="${dl_dir}" >/dev/null 2>&1
	BaiduPCS-Go web --port "${port}" --access >/dev/null 2>&1 &
}

stop() {
	killall BaiduPCS-Go >/dev/null 2>&1
}
