#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sfe[-1]
	add ucitrack sfe
	set ucitrack.@sfe[-1].init=sfe
	commit ucitrack
EOF

sed -i "s/4.14.131/$(uname -r)/g" /usr/lib/lua/luci/model/cbi/flowoffload.lua

[ ! -f /usr/sbin/dnscache ] && ln /usr/sbin/pdnsd /usr/sbin/dnscache
/etc/init.d/sfe enable

rm -f /tmp/luci-indexcache
exit 0
